// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginConfig } from "./PluginConfig";
import type { ScheduleConfig } from "./ScheduleConfig";
import type { SubscriptionConfig } from "./SubscriptionConfig";
import type { TerminalType } from "./TerminalType";
import type { WslShell } from "./WslShell";

export type AppConfig = { shortcut: string, terminal: TerminalType, wslShell: WslShell, lastDirectory: string | null, recentDirectories: Array<string>, wslDirectory: string | null, wslRecentDirectories: Array<string>, schedules: Array<ScheduleConfig>, plugins: Array<PluginConfig>, subscriptions: Array<SubscriptionConfig>, timeoutSecs: bigint, };
