// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecutionSource = { "type": "Schedule", id: string, name: string, } | { "type": "Plugin", pluginName: string, eventType: string, } | { "type": "Manual" };
