// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionSource } from "./ExecutionSource";
import type { ExecutionStatus } from "./ExecutionStatus";

export type ExecutionLog = { id: string, sessionId: string | null, source: ExecutionSource, prompt: string, workingDir: string | null, claudeArgs: Array<string>, status: ExecutionStatus, stdout: string, stderr: string, exitCode: number | null, startedAt: string, completedAt: string | null, durationMs: bigint | null, };
