// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginStatus = { id: string, name: string, running: boolean, pid: number | null, lastEventAt: string | null, error: string | null, lastStderr: string | null, };
