// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScheduleExpression } from "./ScheduleExpression";

export type ScheduleConfig = { id: string, name: string, expression: ScheduleExpression, prompt: string, workingDir: string | null, claudeArgs: Array<string>, enabled: boolean, };
