// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScheduleExpression = { "type": "Cron", expression: string, } | { "type": "Interval", seconds: bigint, } | { "type": "DailyAt", time: string, };
