// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubscriptionConfig = { id: string, name: string, pluginName: string, eventType: string, promptTemplate: string, workingDir: string | null, claudeArgs: Array<string>, enabled: boolean, };
